version: "3.1"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
      - 33060:33060
    restart: always
    volumes:
      - $PWD/mysql/conf.d:/etc/mysql/conf.d  # 配置文件
#      - $PWD/mysql/data:/var/lib/mysql   # 数据存储位置挂载
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # 强制,超级用户账号密码
      MYSQL_DATABASE: monitor # 可选,启动时创建指定的数据库名称
      MYSQL_USER: monitor # 可选,授于指定MYSQL_DATABASE 超级权限
      MYSQL_PASSWORD: 123456 # 可选,授于指定MYSQL_DATABASE 超级权限
      TZ: Asia/Shanghai
  redis:
    image: redis
    volumes:
      - $PWD/redis/conf:/usr/local/etc/redis
      - $PWD/data:/data # 持久化数据挂载
    ports:
      - 6379:6379

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
  grafana:
    image: grafana/grafana
    volumes:
      - $PWD/grafana:/var/lib/grafana # 数据库位置
    ports:
      - 3000:3000
    depends_on:
      - mysql
  nginx:
    image: nginx
    volumes:
      - $PWD/static:/usr/share/nginx/static:ro
      - $PWD/nginx/logs:/var/log/nginx
      - $PWD/nginx:/etc/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=ikratos.com
      - NGINX_PORT=80
    depends_on:
      - grafana
      - prometheus
    command: ['nginx','-g','daemon off;']

  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - $PWD/filebrowser/files:/srv
      - $PWD/filebrowser/database.db:/database.db
      - $PWD/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 9091:9091
    