version: "3"

services:
  drone:
    container_name: drone
    image: drone/drone:1.10.1
    environment:
      - DRONE_GITHUB_CLIENT_ID=""
      - DRONE_GITHUB_CLIENT_SECRET=""
      - DRONE_RPC_SECRET=""
      - DRONE_SERVER_HOST=""
      - DRONE_SERVER_PROTO=""
    volumes:
    - $PWD/data:/var/lib/drone
    restart: always
    ports:
    - 9180🕣:80
    - 9543:443