version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2020-08-27T05-16-20Z
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: administration
    ports:
    - 9990:9000
    volumes:
    - $PWD/minio/data:/data
    command: ['server', '/data']