version: "3"

services:
  mysql:
    image: mysql:8.0.21
    ports:
      - 3306:3306
      - 33060:33060
    restart: on-failure
    volumes:
      - $PWD/mysql/conf.d:/etc/mysql/conf.d  # 配置文件
      - $PWD/mysql/data:/var/lib/mysql   # 数据存储位置挂载
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # 强制,超级用户账号密码
      MYSQL_DATABASE: monitor # 可选,启动时创建指定的数据库名称
      MYSQL_USER: monitor # 可选,授于指定MYSQL_DATABASE 超级权限
      MYSQL_PASSWORD: 123456 # 可选,授于指定MYSQL_DATABASE 超级权限
      TZ: Asia/Shanghai
