# 当前 Pod 的 Labels 字段的值,就会被 Kubernetes 自动挂载成为容器里的 /etc/Podinfo/labels 文件.
apiVersion: v1
kind: Pod
metadata:
  name: test-projected-downwardapi-volume
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
spec:
  containers:
    - name: test-downwardapi-volume
      image: busybox:1.32.0
      command: ["sh", "-c"]
      args:
        - while true; do
          if [[ -e /etc/Podinfo/labels ]]; then
          echo -en '\n\n'; cat /etc/Podinfo/labels; fi;
          sleep 5;
          done;
      volumeMounts:
        - name: Podinfo
          mountPath: /etc/Podinfo
          readOnly: false
  volumes:
    - name: Podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels