apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
    - name: readiness-container
      image: thinkgos/helloworld:v1
      imagePullPolicy: IfNotPresent
      readinessProbe:
        exec:
          command:
            - cat
            - /ready/index.html
        initialDelaySeconds: 5
        timeoutSeconds: 1
      volumeMounts:
        - mountPath: /ready
          name: readyfile
    - name: file-ready
      image: busybox:1.32.0
      command: ["/bin/sh","-c","sleep 5; touch /ready/index.html; sleep 3600"]
      volumeMounts:
        - mountPath: /ready
          name: readyfile
  volumes:
    - name: readyfile
      emptyDir: {}