version: "3.1"

services:
  redis:
    image: redis:6.0.5
    restart: always
    volumes:
      - $PWD/redis/conf:/usr/local/etc/redis
      #- $PWD/redis/data:/data # 持久化数据挂载
    ports:
      - 6379:6379
