version: "3"

services:
  influxdb:
    image: influxdb:1.8.4
    environment:
      - INFLUXDB_DB=telegraf
#      - INFLUXDB_ADMIN_USER=admin
#      - INFLUXDB_ADMIN_PASSWORD=admin
#      - INFLUXDB_USER=thinkgos
#      - INFLUXDB_PASSWORD=thinkgos
#      - INFLUXDB_DATA_ENGINE=tsm1
#      - INFLUXDB_REPORTING_DISABLED=false
#      - INFLUXDB_GRAPHITE_ENABLED=true # 使能 graphite
    volumes:
      - $PWD/data/influxdb:/var/lib/influxdb
#      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - influx_net
    ports:
      - 8086:8086
  chronograf:
    image: chronograf:1.8.8
    volumes:
      - $PWD/data/chronograf:/var/lib/chronograf
    networks:
      - influx_net
    ports:
      - 8888:8888
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:1.17.3
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influx_net
    depends_on:
      - influxdb

networks:
  influx_net:
    driver: bridge