version: "3.1"

services:
  portainer:
    image: portainer/portainer:linux-amd64-1.20.2
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data:/data